AplikacjaDnD/Models/Przygoda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AplikacjaDnD.Models
{
    public enum PoziomTrudnosci
    {
        Latwy,
        Normalny,
        Trudny
    }

    public enum Status
    {
        Rozpoczeta,
        Zakonczona,
        Brak
    }

    [Table("Przygody")]
    public class Przygoda
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdPrzygoda { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        [MaxLength(30)]
        public string Tytul { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        public PoziomTrudnosci PoziomTrudnosci { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        [Range(3,15, ErrorMessage = "W przygodzie moze brac udzial od 3 do 15 graczy")]
        public int LiczbaGraczy { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        [Range(2,10, ErrorMessage = "Liczba lokacji moze wynosic od 2 do 10")]
        public int LiczbaLokacji { get; set; }
        [MaxLength(500)]
        public string Fabula { get; set; }
        [ForeignKey("MistrzGry")]
        public int IdMistrzGry { get; set; }

        public Status Status { get; set; } = Status.Brak;

        public virtual MistrzGry MistrzGry { get; set; }

        public virtual ICollection<Lokacja> Lokacje { get; set; }
        public virtual ICollection<GraczPrzygoda> GraczPrzygody { get; set; }

    }
}

AplikacjaDnD/Controllers/GraczController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplikacjaDnD.Models;
using AplikacjaDnD.Models.ViewModels;

namespace AplikacjaDnD.Controllers
{
    public class GraczController : Controller
    {
        private DbDnD db = new DbDnD();

        // GET: Gracz
        public ActionResult Index()
        {
            int session = (int)Session["UserId"];
            Osoba g = db.Osoby.Where(o => o.IdOsoba == session).First();
            return View(g);
        }

        // GET: Gracz/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = db.Gracze.Include("Postaci").Where(p => p.IdOsoba == id).First();
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // GET: Gracz/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gracz/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdOsoba,Imie,Nazwisko,Nick,Haslo,Email,DataUrodzenia")] Gracz gracz)
        {
            if (ModelState.IsValid)
            {
                db.Osoby.Add(gracz);
                db.SaveChanges();
                return View("GraczUtworzony");
            }

            return View(gracz);
        }

        // GET: Gracz/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = (Gracz)db.Osoby.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // POST: Gracz/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdOsoba,Imie,Nazwisko,Nick,Email,DataUrodzenia")] Gracz gracz)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gracz).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gracz);
        }

        // GET: Gracz/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = (Gracz)db.Osoby.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // POST: Gracz/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gracz gracz = (Gracz)db.Osoby.Find(id);
            db.Osoby.Remove(gracz);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Gracz/Start
        public ActionResult Start()
        {

            return View();
        }

        // POST: Gracz/Start
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Start([Bind(Include = "Nick,Haslo")] StratViewModel start)
        {
            var dbResult = db.Gracze.Where(g => g.Nick.Equals(start.Nick)&&g.Haslo.Equals(start.Haslo));
            

            if (dbResult.Count() > 0)
            {
                var result = dbResult.First();
                Session["UserNick"] = result.Nick;
                Session["UserId"] = result.IdOsoba;
                return View("Menu");
            }

            ModelState.AddModelError("", "Błędny NICK lub HASŁO.");

            return View();
        }

        // POST: Gracz/Start
        
        [HttpPost]
        [ValidateAntiForgeryToken]
       public ActionResult StartDynamic([Bind(Include = "Nick, isMistrzGry")] StratViewModel start)
        {
            var dbResult = db.Osoby.Where(g => g.Nick.Equals(start.Nick));

            if (dbResult.Count() > 0)
            {
                //Tu powinna byc refaktoryzacja, ale zostalo tu dla ulatwienia prezentacji :)
                if (!start.isMistrzGry) {
                    var graczResult = db.Gracze.Where(g => g.Nick.Equals(start.Nick));
                    var result = graczResult.First();
                    result.IsMistrzGry = false;
                    db.Entry(result).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["UserNick"] = result.Nick;
                    Session["UserId"] = result.IdOsoba;
                    return View("Menu");
                } else
                {
                    var graczResult = db.MistrzowieGry.Where(g => g.Nick.Equals(start.Nick));
                    var result = graczResult.First();
                    result.IsMistrzGry = true;
                    db.Entry(result).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["UserNick"] = result.Nick;
                    Session["UserId"] = result.IdOsoba;
                    return View("MenuMistrzGry");
                }
            }

            return View();
        }
       

        public JsonResult IsNickExist(string Nick, int? IdOsoba)
        {
            var validateName = db.Gracze.FirstOrDefault
                                (x => x.Nick == Nick && x.IdOsoba != IdOsoba);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult IsEmailExist(string Email, int? IdOsoba)
        {
            var validateName = db.Gracze.FirstOrDefault
                                (x => x.Email == Email && x.IdOsoba != IdOsoba);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }
        //GET: Gracz/Menu
        public ActionResult Menu()
        {

            return View();
        }

    
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AplikacjaDnD/Controllers/PrzygodaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplikacjaDnD.Models;

namespace AplikacjaDnD.Controllers
{
    public class PrzygodaController : Controller
    {
        private DbDnD db = new DbDnD();

        // GET: Przygoda
        public ActionResult Index()
        {
            var przygody = db.Przygody.Include(p => p.MistrzGry);
            return View(przygody.ToList());
        }

        // GET: Przygoda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przygoda przygoda = db.Przygody.Find(id);
            if (przygoda == null)
            {
                return HttpNotFound();
            }
            return View(przygoda);
        }

        // GET: Przygoda/Create
        public ActionResult Create()
        {
            ViewBag.IdMistrzGry = new SelectList(db.Osoby, "IdOsoba", "Imie");
            return View();
        }

        // POST: Przygoda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPrzygoda,Tytul,PoziomTrudnosci,LiczbaGraczy,LiczbaLokacji,Fabula,IdMistrzGry,Status")] Przygoda przygoda)
        {
            if (ModelState.IsValid)
            {
                db.Przygody.Add(przygoda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdMistrzGry = new SelectList(db.Osoby, "IdOsoba", "Imie", przygoda.IdMistrzGry);
            return View(przygoda);
        }

        // GET: Przygoda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przygoda przygoda = db.Przygody.Find(id);
            if (przygoda == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdMistrzGry = new SelectList(db.Osoby, "IdOsoba", "Imie", przygoda.IdMistrzGry);
            return View(przygoda);
        }

        // POST: Przygoda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPrzygoda,Tytul,PoziomTrudnosci,LiczbaGraczy,LiczbaLokacji,Fabula,IdMistrzGry,Status")] Przygoda przygoda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(przygoda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdMistrzGry = new SelectList(db.Osoby, "IdOsoba", "Imie", przygoda.IdMistrzGry);
            return View(przygoda);
        }

        // GET: Przygoda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przygoda przygoda = db.Przygody.Find(id);
            if (przygoda == null)
            {
                return HttpNotFound();
            }
            return View(przygoda);
        }

        // POST: Przygoda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Przygoda przygoda = db.Przygody.Find(id);
            db.Przygody.Remove(przygoda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DolaczDoPrzygody()
        {
            var przygody = db.Przygody.Include(p => p.MistrzGry).Where(p=>p.Status == Status.Brak);
            return View(przygody.ToList());
        }

        public ActionResult Dolacz(int? idPrzygoda)
        {
            if(idPrzygoda == null)
            {
                return View("DolaczDoPrzygody");
            }

            Przygoda przygoda = db.Przygody.Find(idPrzygoda);
            var idGracz = (int)Session["userId"];

            //----LiczbaGraczy-------
            int liczbaGraczy = PodajLiczbeGraczy(idPrzygoda);

            if (liczbaGraczy >= przygoda.LiczbaGraczy)
            {
                return RedirectToAction("DolaczDoPrzygody");
            }

            //----CzyIstnieje---------
           int graczPrzygoda = SprawdzCzyIstnieje(idGracz, idPrzygoda);
                
            if(graczPrzygoda > 0)
            {
                return View("ErrorGraczPrzygody");
            }

            //----DodanieDoBazy-------
            DodajGraczPrzygoda(idGracz, przygoda);

            //----ZmianaStatusu-------

            if (liczbaGraczy + 1 >= przygoda.LiczbaGraczy)
            {
                ZmianaStatusuPrzygody(liczbaGraczy, przygoda);
            }

            return View( "Koniec");
        }

        public ActionResult Kontynuuj()
        {
            return View("Kontynuuj");
        }
        private int SprawdzCzyIstnieje(int idGracz, int? idPrzygoda)
        {
            var graczPrzygoda = (int)(from gp in db.GraczPrzygody
                                      where gp.IdPrzygoda == idPrzygoda && gp.IdGracz == idGracz
                                      select gp).Count();
                return graczPrzygoda;
        }

        private int PodajLiczbeGraczy(int? idPrzygoda)
        {
            var liczbaGraczy = (int)(from gp in db.GraczPrzygody
                                where gp.IdPrzygoda == idPrzygoda
                                select gp).Count();

            return liczbaGraczy;
        }

        private void DodajGraczPrzygoda(int idGracz, Przygoda przygoda)
        {
            db.GraczPrzygody.Add(new GraczPrzygoda { IdGracz = idGracz, IdPrzygoda = przygoda.IdPrzygoda});
            db.SaveChanges();
        }


        private void ZmianaStatusuPrzygody(int liczbaGraczy, Przygoda przygoda)
        {
            przygoda.Status = Status.Rozpoczeta;
            db.Entry(przygoda).State = EntityState.Modified;
            db.SaveChanges();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AplikacjaDnD/Views/Przygoda/Create.cshtml
@model AplikacjaDnD.Models.Przygoda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Przygoda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tytul, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tytul, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tytul, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoziomTrudnosci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PoziomTrudnosci, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PoziomTrudnosci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LiczbaGraczy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LiczbaGraczy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LiczbaGraczy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LiczbaLokacji, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LiczbaLokacji, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LiczbaLokacji, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fabula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fabula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fabula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdMistrzGry, "IdMistrzGry", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdMistrzGry", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdMistrzGry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AplikacjaDnD/Views/Przygoda/Delete.cshtml
@model AplikacjaDnD.Models.Przygoda

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Przygoda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MistrzGry.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MistrzGry.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tytul)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tytul)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoziomTrudnosci)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoziomTrudnosci)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LiczbaGraczy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiczbaGraczy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LiczbaLokacji)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiczbaLokacji)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fabula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fabula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AplikacjaDnD/Views/Przygoda/Details.cshtml
@model AplikacjaDnD.Models.Przygoda

@{
    ViewBag.Title = "Details";
}
<style>
    .jumbotron {
        background-color: crimson;
        color: #fff;
    }

    .btn-md {
        background-color: #009999;
        border-color: #009999;
    }
</style>


<h2></h2>
<div class="col-lg-12 text-right">
    <img src="~/Images/default-avatar.png" class="img-rounded" alt="Cinque Terre" width="50" height="50">
    <h4>@Session["UserNick"]</h4>
    <h5>Gracz</h5>
</div>
<div class="container">
    <div>
        <h4>Przygoda</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MistrzGry.Imie)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MistrzGry.Imie)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tytul)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tytul)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PoziomTrudnosci)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PoziomTrudnosci)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LiczbaGraczy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LiczbaGraczy)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LiczbaLokacji)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LiczbaLokacji)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fabula)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fabula)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

        </dl>
    </div>
    <p>
        <a class="btn btn-info btn-md" href=@Url.Action("DolaczDoPrzygody", "Przygoda")>Powrót</a>
    <p>
        </div>

AplikacjaDnD/Views/Przygoda/DolaczDoPrzygody.cshtml
@model IEnumerable<AplikacjaDnD.Models.Przygoda>

@{
    ViewBag.Title = "DolaczDoPrzygody";
    Layout = "~/Views/Shared/_LayoutInfo.cshtml";
}
<h2 class="naglowek">wybierz przygodę</h2>
<div id="boxContainer" class="container ceneterContainer">

    <table class="highlight centered responsive-table">
        <tr>
            <th class="center-align">
                Mistrz Gry
            </th>
            <th class="center-align">
                @Html.DisplayNameFor(model => model.Tytul)
            </th>
            <th class="center-align">
                @Html.DisplayNameFor(model => model.PoziomTrudnosci)
            </th>
             <th class="center-align">
                @Html.DisplayNameFor(model => model.LiczbaGraczy)
            </th>
            <th class="center-align">
                @Html.DisplayNameFor(model => model.Fabula)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MistrzGry.Nick)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tytul)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PoziomTrudnosci)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LiczbaGraczy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fabula)
                </td>
                <td>
                    <a class="start waves-effect waves-light btn light-blue darken-3" href=@Url.Action("Dolacz","Przygoda", new { idPrzygoda = item.IdPrzygoda })><i class="material-icons right">send</i>Dołącz</a>
                </td>
            </tr>
        }
    </table>

    <br />
    <br />
    <div class="col-md-6">
        <a class="start waves-effect waves-light btn light-blue darken-3" href=@Url.Action("WybierzPostac", "Postac")>Powrót</a>
    </div>
</div>

AplikacjaDnD/Views/Przygoda/ErrorGraczPrzygody.cshtml
@model AplikacjaDnD.Models.Przygoda

@{
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_LayoutInfo.cshtml";
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

<div class="container ceneterContainer">
    <div id="box">

        <h1 class="naglowek">bierzesz już udział w tej przygodzie!</h1>
        <h3 id="desc" class="center-align">Wybierz inną przygodę.</h3>

        <div class="center-align">

            <div class="center-align">
                <a class="start waves-effect waves-light btn light-blue darken-3" href=@Url.Action("Menu", "Gracz")>Panel gracza</a>
                <a class="start waves-effect waves-light btn light-blue darken-3" href=@Url.Action("DolaczDoPrzygody", "Przygoda")>Wybierz przygodę <i class="material-icons right">send</i></a>
            </div>
        </div>
        </div>
</div>

AplikacjaDnD/Views/Przygoda/Koniec.cshtml
@{
    Layout = "~/Views/Shared/_LayoutInfo.cshtml";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

<div class="container ceneterContainer">
    <div id="box">

        <h1 class="naglowek">przygoda rozpoczęta</h1>
        <h3 id="desc" class="center-align">Koniec przypadku użycia.</h3>

        <div class="center-align">

            <div class="center-align">
                <a class="start waves-effect waves-light btn light-blue darken-3" href=@Url.Action("Menu", "Gracz")>Powrót do strony głównej</a>
            </div>
        </div>
    </div>
</div>

AplikacjaDnD/Views/Przygoda/Kontynuuj.cshtml
@{
    Layout = "~/Views/Shared/_LayoutInfo.cshtml";
}

<div class="container ceneterContainer">
    <div id="box">

        <h1 class="naglowek">kontynuujesz przygodę</h1>
        <h3 id="desc" class="center-align">Koniec przypadku użycia.</h3>

        <div class="center-align">

            <div class="center-align">
                <a class="start waves-effect waves-light btn light-blue darken-3" href=@Url.Action("Menu", "Gracz")>Powrót do strony głównej</a>
            </div>
        </div>
    </div>
</div>