AplikacjaDnD/Controllers/GraczController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplikacjaDnD.Models;
using AplikacjaDnD.Models.ViewModels;

namespace AplikacjaDnD.Controllers
{
    public class GraczController : Controller
    {
        private DbDnD db = new DbDnD();

        // GET: Gracz
        public ActionResult Index()
        {
            int session = (int)Session["UserId"];
            Osoba g = db.Osoby.Where(o => o.IdOsoba == session).First();
            return View(g);
        }

        // GET: Gracz/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = db.Gracze.Include("Postaci").Where(p => p.IdOsoba == id).First();
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // GET: Gracz/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gracz/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdOsoba,Imie,Nazwisko,Nick,Haslo,Email,DataUrodzenia")] Gracz gracz)
        {
            if (ModelState.IsValid)
            {
                db.Osoby.Add(gracz);
                db.SaveChanges();
                return View("GraczUtworzony");
            }

            return View(gracz);
        }

        // GET: Gracz/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = (Gracz)db.Osoby.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // POST: Gracz/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdOsoba,Imie,Nazwisko,Nick,Email,DataUrodzenia")] Gracz gracz)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gracz).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gracz);
        }

        // GET: Gracz/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gracz gracz = (Gracz)db.Osoby.Find(id);
            if (gracz == null)
            {
                return HttpNotFound();
            }
            return View(gracz);
        }

        // POST: Gracz/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gracz gracz = (Gracz)db.Osoby.Find(id);
            db.Osoby.Remove(gracz);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Gracz/Start
        public ActionResult Start()
        {

            return View();
        }

        // POST: Gracz/Start
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Start([Bind(Include = "Nick,Haslo")] StratViewModel start)
        {
            var dbResult = db.Gracze.Where(g => g.Nick.Equals(start.Nick)&&g.Haslo.Equals(start.Haslo));
            

            if (dbResult.Count() > 0)
            {
                var result = dbResult.First();
                Session["UserNick"] = result.Nick;
                Session["UserId"] = result.IdOsoba;
                return View("Menu");
            }

            ModelState.AddModelError("", "Błędny NICK lub HASŁO.");

            return View();
        }

        // POST: Gracz/Start
        
        [HttpPost]
        [ValidateAntiForgeryToken]
       public ActionResult StartDynamic([Bind(Include = "Nick, isMistrzGry")] StratViewModel start)
        {
            var dbResult = db.Osoby.Where(g => g.Nick.Equals(start.Nick));

            if (dbResult.Count() > 0)
            {
                //Tu powinna byc refaktoryzacja, ale zostalo tu dla ulatwienia prezentacji :)
                if (!start.isMistrzGry) {
                    var graczResult = db.Gracze.Where(g => g.Nick.Equals(start.Nick));
                    var result = graczResult.First();
                    result.IsMistrzGry = false;
                    db.Entry(result).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["UserNick"] = result.Nick;
                    Session["UserId"] = result.IdOsoba;
                    return View("Menu");
                } else
                {
                    var graczResult = db.MistrzowieGry.Where(g => g.Nick.Equals(start.Nick));
                    var result = graczResult.First();
                    result.IsMistrzGry = true;
                    db.Entry(result).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["UserNick"] = result.Nick;
                    Session["UserId"] = result.IdOsoba;
                    return View("MenuMistrzGry");
                }
            }

            return View();
        }
       

        public JsonResult IsNickExist(string Nick, int? IdOsoba)
        {
            var validateName = db.Gracze.FirstOrDefault
                                (x => x.Nick == Nick && x.IdOsoba != IdOsoba);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult IsEmailExist(string Email, int? IdOsoba)
        {
            var validateName = db.Gracze.FirstOrDefault
                                (x => x.Email == Email && x.IdOsoba != IdOsoba);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }
        //GET: Gracz/Menu
        public ActionResult Menu()
        {

            return View();
        }

    
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AplikacjaDnD/Controllers/PostacController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplikacjaDnD.Models;

namespace AplikacjaDnD.Controllers
{
    public class PostacController : Controller
    {
        private DbDnD db = new DbDnD();

        // GET: Postac
        public ActionResult Index()
        {
            var idGracz = (int)Session["UserId"];
           // var postaci = db.Postaci.Include(p => p.Gracz).Include(p => p.Klasa).Include(p => p.Rasa);

            var result = from p in db.Postaci
                         where p.IdGracz == idGracz
                         select p;

            return View(result.ToList());
        }

        // GET: Postac/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postac postac = db.Postaci.Find(id);
            if (postac == null)
            {
                return HttpNotFound();
            }
            return View(postac);
        }

        // GET: Postac/Create
        public ActionResult Create()
        {
            ViewBag.IdGracz = new SelectList(db.Osoby, "IdOsoba", "Nick");
            ViewBag.IdKlasa = new SelectList(db.Klasy, "IdKlasa", "Nazwa");
            ViewBag.IdRasa = new SelectList(db.Rasy, "IdRasa", "Nazwa");
         
            return View();
        }

        // POST: Postac/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPostac,IdKlasa,IdRasa,Nazwa,Poziom,PoziomZdrowia,PoziomMany,Doswiadczenie")] Postac postac)
        {
            if (ModelState.IsValid)
            {
                postac.IdGracz = (int)Session["UserId"];
                db.Postaci.Add(postac);
                db.SaveChanges();
                return View("PostacUtworzona");
            }

            ViewBag.IdGracz = new SelectList(db.Osoby, "IdOsoba", "Nick", postac.IdGracz);
            ViewBag.IdKlasa = new SelectList(db.Klasy, "IdKlasa", "Nazwa", postac.IdKlasa);
            ViewBag.IdRasa = new SelectList(db.Rasy, "IdRasa", "Nazwa", postac.IdRasa);
            return View(postac);
        }

        // GET: Postac/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postac postac = db.Postaci.Find(id);
            if (postac == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdGracz = new SelectList(db.Osoby, "IdOsoba", "Nick", postac.IdGracz);
            ViewBag.IdKlasa = new SelectList(db.Klasy, "IdKlasa", "Nazwa", postac.IdKlasa);
            ViewBag.IdRasa = new SelectList(db.Rasy, "IdRasa", "Nazwa", postac.IdRasa);
            return View(postac);
        }

        // POST: Postac/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPostac,IdGracz,IdKlasa,IdRasa,Nazwa,Poziom,PoziomZdrowia,PoziomMany,Doswiadczenie")] Postac postac)
        {
            if (ModelState.IsValid)
            {
                db.Entry(postac).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdGracz = new SelectList(db.Osoby, "IdOsoba", "Nick", postac.IdGracz);
            ViewBag.IdKlasa = new SelectList(db.Klasy, "IdKlasa", "Nazwa", postac.IdKlasa);
            ViewBag.IdRasa = new SelectList(db.Rasy, "IdRasa", "Nazwa", postac.IdRasa);
            return View(postac);
        }

        // GET: Postac/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postac postac = db.Postaci.Find(id);
            if (postac == null)
            {
                return HttpNotFound();
            }
            return View(postac);
        }

        // POST: Postac/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Postac postac = db.Postaci.Find(id);
            db.Postaci.Remove(postac);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult WybierzPostac()
        {
            var idGracz = (int)Session["UserId"];
            var result = (from p in db.Postaci
                          where p.IdGracz == idGracz
                          select p).Count();

            if (result == 0)
            {
                return View("BrakPostaci");
            }

            var postaci = db.Postaci.Include(p => p.Gracz).Include(p => p.Klasa).Include(p => p.Rasa).Where(p => p.IdGracz == idGracz);  
            return View(postaci.ToList());
        }

        public ActionResult WybierzPostacKontynuuj()
        {
            var idGracz = (int)Session["UserId"];
            var result = (from p in db.Postaci
                          where p.IdGracz == idGracz
                          select p).Count();

            if (result == 0)
            {
                return View("BrakPostaci");
            }

            var postaci = db.Postaci.Include(p => p.Gracz).Include(p => p.Klasa).Include(p => p.Rasa).Where(p => p.IdGracz == idGracz);

            return View(postaci.ToList());
        }

        public ActionResult Wybierz(int? id)
        {
            if (id == null)
            {
                return View("WybierzPostac");
            }

            return View("DolaczDoPrzygody", "Przygoda");
        }

        public JsonResult IsNazwaExist(string Nazwa, int? Id)
        {
            var validateName = db.Postaci.FirstOrDefault
                                (x => x.Nazwa == Nazwa && x.IdPostac != Id);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AplikacjaDnD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Megrim" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,600" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/gracz")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)

</head>

<body>
        <nav>
            <div class="nav-wrapper blue-grey darken-4">
                <a href=@Url.Action("Index", "Home") class="brand-logo">Plaguelands </a>
            </div>
        </nav>



        @RenderBody()


        <footer class="blue-grey darken-4">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="logo">Plaguelands</h5>
                        <p id="foot" class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis aliquam elit, quis semper mauris. Mauris et placerat lacus.</p>
                    </div>
                    <div  id="footerLinks" class="col l4 offset-l2 s12">
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">Kontakt</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Pomoc</li>
                            <li><a class="grey-text text-lighten-3" href="#!">Regulamin</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container white-text">
                    <p id="copy">Copyright © Plaguelands Project 2019. All Rights Reseverd.</p>
                </div>
            </div>
        </footer>

</body>
</html>

AplikacjaDnD/Views/Shared/_LayoutInfo.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Megrim" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,600" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kontogracz")
    @Styles.Render("~/Content/buttoneffect")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)

</head>

<body>
    <ul id="dropdown1" class="dropdown-content">
        <li>@Html.ActionLink("moje konto", "Index", "Gracz")</li>
        <li>@Html.ActionLink("lista postaci", "Index", "Postac")</li>
        <li>@Html.ActionLink("rozpoczęte przygody", "RozpoczetePrzygody", "GraczPrzygoda")</li>
        <li>@Html.ActionLink("zakończone przygody", "ZakonczonePrzygody", "GraczPrzygoda")</li>
        <li>@Html.ActionLink("zakończ", "Index", "Home")</li>
    </ul>
    <nav>
        <div class="nav-wrapper blue-grey darken-4">
            <a href=@Url.Action("Menu", "Gracz") class="brand-logo">Plaguelands </a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="barmenu" class="right hide-on-med-and-down">
                <!-- Dropdown Trigger -->
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"> @Session["UserNick"].ToString().ToLower()<i class="material-icons left">account_circle</i></a></li>
            </ul>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        <li>@Html.ActionLink("moje konto", "Index", "Gracz")</li>
        <li>@Html.ActionLink("lista postaci", "Index", "Postac")</li>
        <li>@Html.ActionLink("rozpoczęte przygody", "RozpoczetePrzygody", "GraczPrzygoda")</li>
        <li>@Html.ActionLink("zakończone przygody", "ZakonczonePrzygody", "GraczPrzygoda")</li>
        <li>@Html.ActionLink("zakończ", "Index", "Home")</li>
    </ul>


        @RenderBody()


        <footer class="blue-grey darken-4">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="logo">Plaguelands</h5>
                        <p id="foot" class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis aliquam elit, quis semper mauris. Mauris et placerat lacus.</p>
                    </div>
                    <div id="footerLinks" class="col l4 offset-l2 s12">
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">Kontakt</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Pomoc</li>
                            <li><a class="grey-text text-lighten-3" href="#!">Regulamin</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container white-text">
                    <p id="copy">Copyright © Plaguelands Project 2019. All Rights Reseverd.</p>
                </div>
            </div>
        </footer>

</body>
</html>

AplikacjaDnD/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Megrim" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,600" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/home")


</head>

<body>
    <nav>
        <div class="nav-wrapper blue-grey darken-4">
            <a href="#!" class="brand-logo">Plaguelands </a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="barmenu"class="right hide-on-med-and-down">
                        <li>@Html.ActionLink("dołącz", "Create", "Gracz")</li>
                        <li>@Html.ActionLink("Rozpocznij", "Start", "Gracz")</li>
            </ul>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        <li>@Html.ActionLink("Dołącz", "Create", "Gracz")</li>
        <li>@Html.ActionLink("Rozpocznij", "Start", "Gracz")</li>
    </ul>



    @RenderBody()
  
    <footer class="blue-grey darken-4">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="logo">Plaguelands</h5>
                    <p id="foot" class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis aliquam elit, quis semper mauris. Mauris et placerat lacus.</p>
                </div>
                <div  id="footerLinks" class="col 14 offset-l2 s12">
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Kontakt</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Pomoc</li>
                        <li><a class="grey-text text-lighten-3" href="#!">Regulamin</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container white-text">
               <p id="copy">Copyright © Plaguelands Project 2019. All Rights Reseverd.</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")

</body>
</html>